theme: jekyll-theme-hacker
author: kay
blogName: "zerokay"
title: "zerokay's Blog: Computer Security and Various Thoughts."
description: "zerokay -> ok -> Absolute Zero && Anything is Possible"
github_username: kay
