theme: jekyll-theme-hacker
author: kay
blogName: 0k
title: "zer0kay's Blog: Computer Security and Various Thoughts."
description: "zer0kay -> 0k -> Absolute Zero && Anything is Possible."
github_username: kay
